services:
  builder:
    container_name: BrickRecover-builder
    build:
      context: .
      dockerfile: dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ..:/project:rw,Z
      - node_modules_volume:/project/node_modules:rw
    working_dir: /project
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - CI=true

volumes:
  node_modules_volume:
